//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReComp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class REEntities : DbContext
    {
        public REEntities()
            : base("name=REEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Home1> Home1 { get; set; }
        public virtual DbSet<Home1Image> Home1Image { get; set; }
        public virtual DbSet<Home2> Home2 { get; set; }
        public virtual DbSet<Home3> Home3 { get; set; }
        public virtual DbSet<Home3Head> Home3Head { get; set; }
        public virtual DbSet<Home4> Home4 { get; set; }
        public virtual DbSet<Home5> Home5 { get; set; }
        public virtual DbSet<Project1> Project1 { get; set; }
        public virtual DbSet<Project1Image> Project1Image { get; set; }
        public virtual DbSet<Project2> Project2 { get; set; }
        public virtual DbSet<Project3> Project3 { get; set; }
        public virtual DbSet<Project3Head> Project3Head { get; set; }
    }
}
