//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReComp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project1
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string MainText { get; set; }
        public string sec1 { get; set; }
        public string sec2 { get; set; }
        public string sec3 { get; set; }
        public string sec4 { get; set; }
        public string sec5 { get; set; }
        public string sec6 { get; set; }
        public string Details { get; set; }
    }
}
