//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReComp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project3
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public string SubTitle { get; set; }
        public string Ft { get; set; }
        public string Bed { get; set; }
        public string Bath { get; set; }
        public string Garage { get; set; }
    }
}
