//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReComp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int İD { get; set; }
        public int Type_İD { get; set; }
        public int Stick_İD { get; set; }
        public string Area { get; set; }
    
        public virtual Room_Type Room_Type { get; set; }
        public virtual Sticker Sticker { get; set; }
    }
}
