//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReComp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sticker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sticker()
        {
            this.Rooms = new HashSet<Room>();
            this.Stick_Photo = new HashSet<Stick_Photo>();
            this.Sells = new HashSet<Sell>();
        }
    
        public int İD { get; set; }
        public string Name { get; set; }
        public int Project_İD { get; set; }
        public string Price { get; set; }
        public string Short_info { get; set; }
        public int Type_İD { get; set; }
        public string Area { get; set; }
        public Nullable<bool> GarageStatus { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stick_Photo> Stick_Photo { get; set; }
        public virtual Stick_Type Stick_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sell> Sells { get; set; }
    }
}
