//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReComp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stick_sxem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Stick_Id { get; set; }
    
        public virtual Sticker Sticker { get; set; }
    }
}
